baseUrl: "/"
title: BLOG/K8150.NET
paginate: 10
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10

params:
  env: production
  description: ""
  author: koji haigo
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      Welcome to **BLOG/K8150.NET**.

      - **BLOG/K8150.NET** is a simple but fast and responsive theme with useful feature-set that enhances UX.
  socialIcons:
    - name: twitter
      url: "https://twitter.com/k8150_"
    - name: github
      url: "https://github.com/k8150"

taxonomies:
  category: categories
  tag: tags
  series: series

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true